---
title: "Behavioral segmentation error rates"
author: "Emma Fuller"
date: "October 3, 2014"
output: pdf_document
bibliography: refs.bib
---

@walker2010pioneer has a 10% misclassification rate. 

+ Purse seiners in Indian Oceans (15 in 2006, 17 in 2007)
+ Data was GPS, every hour
+ Speed and turning angle between reloactions was calculated
+ Speed was rescaled to be between 0 and 1 where 1 is equivalent to max speeds, 12 knots
+ Fishing only occurs during the day, so only daytime parts of trajectories were used
+ Used one observered trip to calibrate the models
+ Assumed 4 states: fishing operation (> 1 hr; unsuccesful 1.65 hrs, successful scales with amount of catch), stop at sea (could either have to do with fishing or maintance), tracking (tourtious), and cruising.
+ Calibration of models just in terms of fishing versus not fishing (only one state is strictly fishing)
+ Fit HMMs to each vessel independently. 

Other references, state space models

+ Ovaskainen and Hanski, 2001
+ Buckland et al., 2004
+ Thomas et al., 2005
+ Patterson et al., 2008
+ Morales et al., 2004

## General notes

+ One usually distinguishes two different frameworks for analysing trajectories (Turchin, 1998, pp. 127-134). In the step by step approach, trajectories are regularly sampled at a resolution given by the size of the steps in time. The true track between two samples (recording positions) is not known and the distributions of apparent speeds and turning angles provided by the observations are different from the true ones and vary with the step value (the homogeneity of the time resolution for the steps is thus fundamental). Alternatively, one can define the parts of the trajectory with constant speed and direction (moves). Moves are defined by con-stant speed and direction between two breaking points. The tracks between two breaking points are known and linear (up to some unavoidable tolerances needed in practice) [@walker2010pioneer]. 
  + we have instantaneous estimates of speed, slightly different

## Bibliography